export const drinksActionTypes = {
  FETCH_DRINKS_REQUEST: "FETCH_DRINKS_REQUEST",
  FETCH_DRINKS_SUCCESS: "FETCH_DRINKS_SUCCESS",
  FETCH_DRINKS_FAILURE: "FETCH_DRINKS_FAILURE",
  FILTER_DRINKS: "FILTER_DRINKS",
  SET_DRINK_CATEGORY: "SET_DRINK_CATEGORY",
};
